server:
  port:80

spring:
  h2:
    console:
    enabled: true
    path: /h2-console

  jpa:
    database: mysql   # 추가 해준 부분
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 추가 해준 부분
    show-sql: true

    hibernate:
      ddl-auto: update
    generate-ddl: true

    properties:
      dialect:
        #org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        format_sql: true
        
#  datasource:
#    url: jdbc:mysql://database-1.c78kyz1h0q9p.us-east-2.rds.amazonaws.com:3306/testDB?createDatabaseIfNotExist=true
#    username: waganawa
#    password: youareadie2!A
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://database-1.c78kyz1h0q9p.us-east-2.rds.amazonaws.com:3306/testDB_new_test1?createDatabaseIfNotExist=true
    username: waganawa
    password: youareadie2!A
    driver-class-name: com.mysql.cj.jdbc.Driver

handlebars:
  suffix: .html
  expose-session-attribute: true